{
  "props": {
    "version": "1.0",
    "author": "Mapicom Development Team"
  },
  "components": {
    "downloader": {
      "type": "bundle\\http\\HttpDownloader",
      "x": 128,
      "y": 32,
      "props": {
        "useTempFile": false,
        "threadCount": 1
      }
    },
    "dirChooser": {
      "type": "script\\DirectoryChooserScript",
      "x": 32,
      "y": 32,
      "props": {
        "title": "Выберите папку с игрой",
        "inputNode": "",
        "actionNode": ""
      }
    }
  }
}