{
  "props": {
    "version": "1.0",
    "author": "Mapicom Development Team"
  },
  "components": {
    "downloader": {
      "type": "bundle\\http\\HttpDownloader",
      "x": 128.0,
      "y": 32.0,
      "props": {
        "useTempFile": false,
        "threadCount": "4"
      }
    },
    "dirChooser": {
      "type": "script\\DirectoryChooserScript",
      "x": 32.0,
      "y": 32.0,
      "props": {
        "title": "Выберите папку с игрой",
        "inputNode": "",
        "actionNode": ""
      }
    }
  }
}